### ISSUE TITLE
disk image is corrupted on MacOS Monterey 

### ISSUE THREAD

**Issue by abczefg** [openforis/collect-earth#17]
After downloading the installation package, it says the disk image is corrupted.
Is it an issue of compatibility?

**Comment by herrtunante** [comment]
Thanks for reporting.
We just released version 1.14.5 generated with a newer version of InstallBuilder that should create Monterey-compatible installer. Could you please test it (I do not have a Monterey compatible Mac at hand right now)? Just download from the website or [follow this link](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=org.openforis.collect.earth&a=collect-earth-installer&v=LATEST&c=osx&e=dmg)

**Comment by abczefg** [comment]
Dear Alonso,
I got the same error message:
zhuo
[image: Screenshot 2021-12-19 at 16.13.02.png]

**Comment by abczefg** [comment]
Sorry, Alfonso *

**Comment by abczefg** [comment]
Now it's solved!

**Comment by herrtunante** [comment]
Great! How did you manage to fix it (so that I can advice other users with the same issue)?

**Comment by abczefg** [comment]
I wasn't very sure what was the real issue, but my Monterey version is
12.0.1 (21A559). The dmg file I downloaded from collect earth website has
285 megabytes. I asked a friend of mine who uses Monterey version 12.0.1
without the parenthesis to download and he had no problem installing it. So
I asked him to send the dmg to me via skype, and the file I received has
217 megabytes. (I don't understand, do you know why so?)  And with that dmg
file I could install it without any problem. Now I have upgraded my system
again to Monterey 12.0.1 without the parenthesis. And I download the dmg,
still corrupted. I tried to use the Disk Utility to verify it. Not working.
So it's not very clear to me which part was wrong. The good news is that
other people might not have the same issue :)

**Comment by abczefg** [comment]
Hi Alfonso,
I am embarrassed because I just realized the app I downloaded was Collect,
not Collect Earth.
Then I tried to install again on my macbook (Monterey 12.1), but it says
the dmg is corrupted. I tested on another macbook with the same system, and
got the same message.
I am afraid this version of Collect Earth is not compatible with Monterey,
or there's something wrong with the file. Could you please take a look at
the issue?
Thank you.
Zhuo

**Comment by herrtunante** [comment]
Hi again Zhuo,

I just release a new version, could you please download it again and try?
Sorry for the inconvenience.
https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=org.openforis.collect.earth&a=collect-earth-installer&v=LATEST&c=osx&e=dmg 

Alfonso

**Comment by herrtunante** [comment]
If the newest version does not work, I also found this other possible fix  : https://youtu.be/vXzLNDgcVRI?t=44 
Could you test please?

**Comment by abczefg** [comment]
Dear Alfonso,
Unfortunately I still get the same error message of this new version (see
screenshot). It doesn't seem to be related to security reasons and I tried
to troubleshoot it before but was not lucky.
Zhuo
[image: Screenshot 2022-01-17 at 13.37.52.png]

**Comment by herrtunante** [comment]
The newest installer for Collect Earth (1.14.8) has finally fixed the issue with installation on Monterey!

This is probably too late for user *perla*, our apologies for making you wait but the bug originated from the software 
that we use to generate the installers so we had to wait for them to fix it.

LATES VERSION OF COLLECT EARTH FOR MAC **[DOWNLOAD LINK][1]**


  [1]: https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=org.openforis.collect.earth&a=collect-earth-installer&v=LATEST&c=osx&e=dmg
