### ISSUE TITLE
GEE customization

### ISSUE THREAD

**Issue by nanshany** [openforis/collect-earth#3]
Dear OF team,

Is it possible to display the Google Earth Engine Code with my own customization? I want to use my own designed charts and maps.

**Comment by herrtunante** [comment]
Hi nanshani,
check the answer in the forum : http://www.openforis.org/support/questions/330/how-to-run-my-own-google-earth-engine-playground-script-when-clicking-on-a-plot?page=1&focusedAnswerId=2371#2371

Could you please try to comment in the answer to see if that works for you? Still having problems fixing the forum. Thanks
